export const DATA_ALREADY_EXISTS = "DATA_ALREADY_EXISTS";

export const FETCH_SINGLE_POST = "FETCH_SINGLE_POST";
export const FETCH_POSTS_BY_OWNER = "FETCH_POSTS_BY_OWNER";
export const FETCH_POSTS_BY_FOLLOWINGS = "FETCH_POSTS_BY_FOLLOWINGS";
export const TOGGLE_LIKE = "TOGGLE_LIKE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const FETCH_SINGLE_USER = "FETCH_SINGLE_USER";
export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const TOGGLE_FOLLOWING = "TOGGLE_FOLLOWING";
