export const FETCH_POSTS = "FETCH_POSTS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const FETCH_SINGLE_USER = "FETCH_SINGLE_USER";
